version: '3.9'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b2b-back
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: b2b-db
    restart: always
    env_file:
      - .env
    ports:
      - "3106:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:

